#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$HOME/.config/opencode-profiles"

echo "=== Installing OpenCode Profile-Based Agent Teams ==="

# Create profile config directories
mkdir -p "$CONFIG_DIR"/{orchestrator,planning,engineering,validation}

# Symlink profile contents
for profile in orchestrator planning engineering validation; do
  echo "Installing profile: $profile"
  ln -sf "$REPO_DIR/profiles/$profile/opencode.json" "$CONFIG_DIR/$profile/opencode.json"
  ln -sf "$REPO_DIR/profiles/$profile/agents" "$CONFIG_DIR/$profile/agents"
  ln -sf "$REPO_DIR/profiles/$profile/skills" "$CONFIG_DIR/$profile/skills"
  ln -sf "$REPO_DIR/profiles/$profile/rules" "$CONFIG_DIR/$profile/rules"
  
  # Create .opencode symlinks (OpenCode expects .opencode/ prefix)
  mkdir -p "$CONFIG_DIR/$profile/.opencode"
  ln -sf "../agents" "$CONFIG_DIR/$profile/.opencode/agents"
  ln -sf "../skills" "$CONFIG_DIR/$profile/.opencode/skills"
  ln -sf "../rules" "$CONFIG_DIR/$profile/.opencode/rules"
done

# Symlink shared resources to each profile
for profile in orchestrator planning engineering validation; do
  ln -sf "$REPO_DIR/shared/skills" "$CONFIG_DIR/$profile/shared-skills"
  ln -sf "$REPO_DIR/shared/rules" "$CONFIG_DIR/$profile/shared-rules"
done

# Add aliases to shell config
SHELL_RC="$HOME/.zshrc"
if [ ! -f "$SHELL_RC" ]; then
  SHELL_RC="$HOME/.bashrc"
fi

echo "" >> "$SHELL_RC"
echo "# OpenCode Profile Aliases (auto-generated by install.sh)" >> "$SHELL_RC"
echo "alias oc-orchestrator='OPENCODE_CONFIG_DIR=$CONFIG_DIR/orchestrator opencode'" >> "$SHELL_RC"
echo "alias oc-planning='OPENCODE_CONFIG_DIR=$CONFIG_DIR/planning opencode'" >> "$SHELL_RC"
echo "alias oc-engineering='OPENCODE_CONFIG_DIR=$CONFIG_DIR/engineering opencode'" >> "$SHELL_RC"
echo "alias oc-validation='OPENCODE_CONFIG_DIR=$CONFIG_DIR/validation opencode'" >> "$SHELL_RC"


echo ""
echo "=== Installation complete ==="
echo "Restart shell to load aliases, then run:"
echo "  oc-orchestrator"
echo "  oc-planning"
echo "  oc-engineering"
echo "  oc-validation"
echo ""
echo "Or spawn all profiles at once:"
echo ""
echo "Or use Herdr:"
echo "  herdr new-session --name orchestrator -- cmd oc-orchestrator"
echo "  herdr new-session --name planning -- cmd oc-planning"
echo "  herdr new-session --name engineering -- cmd oc-engineering"
echo "  herdr new-session --name validation -- cmd oc-validation"
