#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$HOME/.config/opencode-profiles"

echo "=== Installing OpenCode Profile-Based Agent Teams ==="

# Create profile config directories
mkdir -p "$CONFIG_DIR"/{orchestrator,planning,engineering,validation}

# Symlink profile contents
for profile in orchestrator planning engineering validation; do
  echo "Installing profile: $profile"
  ln -sf "$REPO_DIR/profiles/$profile/opencode.json" "$CONFIG_DIR/$profile/opencode.json"
  ln -sf "$REPO_DIR/profiles/$profile/agents" "$CONFIG_DIR/$profile/agents"
  ln -sf "$REPO_DIR/profiles/$profile/skills" "$CONFIG_DIR/$profile/skills"
  ln -sf "$REPO_DIR/profiles/$profile/rules" "$CONFIG_DIR/$profile/rules"
  
  # Remove any rogue recursive skills/skills symlink
  rm -f "$REPO_DIR/profiles/$profile/skills/skills"
  # Create .opencode symlinks (OpenCode expects .opencode/ prefix)
  mkdir -p "$CONFIG_DIR/$profile/.opencode"
  rm -rf "$CONFIG_DIR/$profile/.opencode/agents" "$CONFIG_DIR/$profile/.opencode/skills" "$CONFIG_DIR/$profile/.opencode/rules"
  ln -sf "../agents" "$CONFIG_DIR/$profile/.opencode/agents"
  ln -sf "../skills" "$CONFIG_DIR/$profile/.opencode/skills"
  ln -sf "../rules" "$CONFIG_DIR/$profile/.opencode/rules"
done

# Symlink shared resources to each profile
for profile in orchestrator planning engineering validation; do
  ln -sf "$REPO_DIR/shared/skills" "$CONFIG_DIR/$profile/shared-skills"
  ln -sf "$REPO_DIR/shared/rules" "$CONFIG_DIR/$profile/shared-rules"
done

# Add/update aliases in shell config (idempotent)
SHELL_RC="$HOME/.zshrc"
if [ ! -f "$SHELL_RC" ]; then
  SHELL_RC="$HOME/.bashrc"
fi

ALIAS_BLOCK=$(cat <<-EOF

# OpenCode Profile Aliases (auto-generated by install.sh)
alias oc-orchestrator='OPENCODE_CONFIG_DIR=$CONFIG_DIR/orchestrator opencode'
alias oc-planning='OPENCODE_CONFIG_DIR=$CONFIG_DIR/planning opencode'
alias oc-engineering='OPENCODE_CONFIG_DIR=$CONFIG_DIR/engineering opencode'
alias oc-validation='OPENCODE_CONFIG_DIR=$CONFIG_DIR/validation opencode'
# /OpenCode Profile Aliases
EOF
)

if grep -q "# OpenCode Profile Aliases (auto-generated by install.sh)" "$SHELL_RC" 2>/dev/null; then
  # Replace existing block
  sed -i '/^# OpenCode Profile Aliases (auto-generated by install.sh)$/,/^# \/OpenCode Profile Aliases$/d' "$SHELL_RC"
  echo "$ALIAS_BLOCK" >> "$SHELL_RC"
else
  echo "$ALIAS_BLOCK" >> "$SHELL_RC"
fi


echo ""
echo "=== Installation complete ==="
echo "Restart shell to load aliases, then run:"
echo "  oc-orchestrator"
echo "  oc-planning"
echo "  oc-engineering"
echo "  oc-validation"
echo ""
echo "Or spawn all profiles at once:"
echo ""
echo "Or use Herdr:"
echo "  herdr new-session --name orchestrator -- cmd oc-orchestrator"
echo "  herdr new-session --name planning -- cmd oc-planning"
echo "  herdr new-session --name engineering -- cmd oc-engineering"
echo "  herdr new-session --name validation -- cmd oc-validation"
